name: altoque
description: "ALTOQUE - App de emergencias para Perú. Contacta servicios de emergencia con un solo toque."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17
  flutter_animate: ^4.5.2

  # Navigation
  go_router: ^15.1.2

  # Platform Services
  url_launcher: ^6.3.1
  shared_preferences: ^2.5.3
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  speech_to_text: ^7.4.0
  firebase_core: ^4.12.1
  cloud_firestore: ^6.7.1
  firebase_ai: ^3.14.1
  firebase_app_check: ^0.4.5+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
