// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGcEA568BruHt5ofYgozF2RPVm44V0WZk',
    appId: '1:550248545136:web:ed8ab18bfebbd631606db5',
    messagingSenderId: '550248545136',
    projectId: 'altoque-emergencias',
    authDomain: 'altoque-emergencias.firebaseapp.com',
    storageBucket: 'altoque-emergencias.firebasestorage.app',
    measurementId: 'G-XMBQMMKSFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJFsG_ECYFFSMtPi2jFB4MlqbtTFUXNVY',
    appId: '1:550248545136:android:c6d2e2fa5c056b98606db5',
    messagingSenderId: '550248545136',
    projectId: 'altoque-emergencias',
    storageBucket: 'altoque-emergencias.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBq7LXLUJGL3pX9aMbsEKiSwveNxLbtQsg',
    appId: '1:550248545136:ios:fb6d33868336108e606db5',
    messagingSenderId: '550248545136',
    projectId: 'altoque-emergencias',
    storageBucket: 'altoque-emergencias.firebasestorage.app',
    iosBundleId: 'com.altoque.altoque',
  );
}
